#!/bin/sh

# Skip running release if the last commit was a version bump
if git log -1 --pretty=%B | grep -q "chore(release)"; then
  echo "Skipping version bump to avoid infinite loop"
  exit 0
fi
npm test && npm run release && git push --follow-tags
