name: Prepare Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Generate release files
        run: |
          set +e
          OUTPUT=$(npx standard-version --skip.tag --skip.commit 2>&1)
          STATUS=$?
          echo "$OUTPUT"
          if [ $STATUS -ne 0 ]; then
            if echo "$OUTPUT" | grep -qi "no changes found"; then
              exit 0
            else
              exit $STATUS
            fi
          fi

      - name: Detect changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Get new version
        id: version
        if: steps.changes.outputs.changed == 'true'
        run: |
          echo "value=$(node -p \"require('./package.json').version\")" >> "$GITHUB_OUTPUT"

      - name: Create release PR
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: chore(release): v${{ steps.version.outputs.value }}
          branch: release/v${{ steps.version.outputs.value }}
          title: chore(release): v${{ steps.version.outputs.value }}
          body: |
            ## Summary
            - Automated version bump and changelog update.
            - Generated by GitHub Actions after changes merged to `main`.
          labels: release
          delete-branch: true
