name: Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'chore(release)')
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Determine version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "value=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Check for existing tag
        id: tag-check
        run: |
          TAG="v${{ steps.version.outputs.value }}"
          if git ls-remote --tags origin "$TAG" | grep -q "$TAG"; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create and push tag
        if: steps.tag-check.outputs.exists == 'false'
        env:
          TAG: v${{ steps.version.outputs.value }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$TAG"
          git push origin "$TAG"
